create table public.profiles (
  id uuid not null,
  created_datetime_utc timestamp with time zone null default now(),
  modified_datetime_utc timestamp with time zone null,
  first_name character varying null,
  last_name character varying null,
  email text null,
  is_superadmin boolean not null default false,
  is_in_study boolean not null default false,
  is_matrix_admin boolean not null default false,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;





create table public.images (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone null,
  url character varying null,
  is_common_use boolean null default false,
  profile_id uuid null default auth.uid (),
  additional_context character varying null,
  is_public boolean null default false,
  image_description text null,
  celebrity_recognition text null,
  embedding public.vector null,
  constraint images_pkey primary key (id),
  constraint images_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_images_is_common_use on public.images using btree (is_common_use) TABLESPACE pg_default
where
  (is_common_use = true);

create index IF not exists idx_images_is_public on public.images using btree (is_public) TABLESPACE pg_default
where
  (is_public = true);

create index IF not exists idx_images_profile_id on public.images using btree (profile_id) TABLESPACE pg_default;




create table public.captions (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone null,
  content character varying null,
  is_public boolean not null,
  profile_id uuid not null,
  image_id uuid not null,
  humor_flavor_id bigint null,
  is_featured boolean not null default false,
  caption_request_id bigint null,
  like_count bigint not null default '0'::bigint,
  llm_prompt_chain_id bigint null,
  constraint captions_pkey primary key (id),
  constraint captions_caption_request_id_fkey foreign KEY (caption_request_id) references caption_requests (id) on update CASCADE on delete CASCADE,
  constraint captions_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete set null,
  constraint captions_image_id_fkey foreign KEY (image_id) references images (id) on delete CASCADE,
  constraint captions_llm_prompt_chain_id_fkey foreign KEY (llm_prompt_chain_id) references llm_prompt_chains (id) on delete CASCADE,
  constraint captions_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_captions_image_id on public.captions using btree (image_id) TABLESPACE pg_default;

create index IF not exists idx_captions_like_count_desc_id on public.captions using btree (like_count desc, id) TABLESPACE pg_default;

create index IF not exists captions_image_id_idx on public.captions using btree (image_id) TABLESPACE pg_default;


create table public.caption_votes (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null,
  modified_datetime_utc timestamp with time zone null,
  vote_value smallint not null,
  profile_id uuid not null,
  caption_id uuid not null,
  user_id uuid null,
  value smallint null,
  created_at timestamp with time zone null default now(),
  constraint caption_votes_pkey primary key (id),
  constraint caption_votes_caption_id_user_id_key unique (caption_id, user_id),
  constraint caption_votes_caption_id_fkey foreign KEY (caption_id) references captions (id) on delete CASCADE,
  constraint caption_votes_profile_id_fkey foreign KEY (profile_id) references profiles (id)
) TABLESPACE pg_default;

create unique INDEX IF not exists caption_votes_user_caption_unique on public.caption_votes using btree (profile_id, caption_id) TABLESPACE pg_default;

create index IF not exists caption_votes_caption_id_idx on public.caption_votes using btree (caption_id) TABLESPACE pg_default;

create index IF not exists caption_votes_user_id_idx on public.caption_votes using btree (user_id) TABLESPACE pg_default;

create trigger trg_caption_like_counter
after INSERT
or DELETE
or
update on caption_votes for EACH row
execute FUNCTION caption_like_counter_tg ();



create table public.sidechat_posts (
  id uuid not null,
  created_datetime_utc timestamp with time zone not null default now(),
  content text null,
  post_datetime_utc timestamp with time zone not null,
  like_count smallint not null default '0'::smallint,
  constraint sidechat_posts_pkey primary key (id)
) TABLESPACE pg_default;create table public.sidechat_posts (
  id uuid not null,
  created_datetime_utc timestamp with time zone not null default now(),
  content text null,
  post_datetime_utc timestamp with time zone not null,
  like_count smallint not null default '0'::smallint,
  constraint sidechat_posts_pkey primary key (id)
) TABLESPACE pg_default;




create table public.humor_flavors (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  description text null,
  slug character varying not null,
  constraint humor_flavors_pkey primary key (id),
  constraint humor_flavors_slug_key unique (slug)
) TABLESPACE pg_default;

